# Generated by Django 2.2.1 on 2020-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='crop',
            name='est_harvest',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='problem',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
