# Generated by Django 2.2.1 on 2020-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_auto_20200128_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.CharField(max_length=100)),
                ('reported_date', models.DateField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
