# Generated by Django 2.2.1 on 2020-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=50)),
                ('user_lname', models.CharField(max_length=50)),
                ('user_uname', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=80, unique=True)),
                ('user_password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
